### ISSUE TITLE
Vertaisarvio 1

### ISSUE THREAD

**Issue by Veloxization** [sapetus/Arvostelusovellus#1]
# Vertaisarvio 1
Testattu 4.4.2022 suunnilleen klo 17 ja 18 välillä.

Upea alku sovellukselle. Käyttöliittymän toiminta on helppo ymmärtää ja navigointi eri valikoiden välillä on tehty helpoksi. Omat huomioni liittyvät sovelluksen tämänhetkiseen tilaan ja saattavat sisältää asioita, jotka on jo paikallisessa versiossa korjattu, tai jotka on suunniteltu, mutta ei vielä implementoitu.

## Löydetyt ongelmat

Jos arvostelussa jättää "Rating"-kentän tyhjäksi, seuraa internal server error. Helppo ratkaisu on laittaa [tänne](https://github.com/sapetus/Arvostelusovellus/blob/0de9b60c494cfdb7dad28121cecb3b5f5facdf6b/app/routes.py#L96) erillinen `if rating is None` tarkistus.

Suosittelen myös jonkinlaisia rajoitteita käyttäjänimiin ja salasanoihin. Pystyin luomaan sekä käyttäjänimiä että salasanoja, joissa oli vain yksi merkki. Sen lisäksi kykenin luomaan käyttäjän, jonka nimessä oli 72 UTF-32 merkkiä.

Sovelluksessa on potentiaalinen CSRF-haavoittuvuus. [Materiaalista](https://hy-tsoha.github.io/materiaali/osa-4/#csrf-haavoittuvuus) löytyy ohjeet tämän ratkaisemiseksi.

### Profiilikuvaa ei pysty vaihtamaan

Laita [tänne](https://github.com/sapetus/Arvostelusovellus/blob/0de9b60c494cfdb7dad28121cecb3b5f5facdf6b/app/utils/picture.py) uusi metodi profiilikuvan vaihtamiseksi. PostgreSQL-komento on seuraavanlainen:
```sql
UPDATE picture SET picture=:picture WHERE user_account_id=:id;
```
`:picture` on kuvadata ja `:id` on käyttäjän uniikki ID.

### Suosikkikategorian vaihto ei onnistu

Tämä voidaan korjata samantapaisella tavalla. Laita [tänne](https://github.com/sapetus/Arvostelusovellus/blob/0de9b60c494cfdb7dad28121cecb3b5f5facdf6b/app/utils/user.py) uusi metodi käyttäjätietojen päivitykselle ja päivitä PostgreSQL-komennolla 
```sql
UPDATE user_information SET value=:favourite_category WHERE key=:key AND user_account_id=:id;
```
`:favourite_category` on uusi suosikkikategoria, `:key` on avain, tässä tapauksessa "favourite_category", ja `:id` on käyttäjän uniikki ID.

## "Quality of life" -ehdotuksia
1. Kun käyttäjä syöttää väärät kirjautumistiedot, lataa liian suuren profiilikuvan tai syöttää virheellistä tietoa uuden median lisäämisessä, käyttäjän täytyy nyt manuaalisesti navigoida takaisin lomakkeeseen. Yhtenä ehdotuksenani olisi laittaa virheviesti kirjautumiskenttien yhteyteen esimerkiksi käyttäen URL-parametrejä tyylillä `?error=JokinVirheJuttu`. Parametrit pystyy nappaamaan Flaskilla tyylillä `request.args.get("parametrin nimi tähän")`. Sitten templatessa voisi tarkistaa tällaisen virheen olemassaolo tavallisella if-lauseella ja näyttää tekstiä sen mukaisesti.

    Vaihtoehtoisesti käyttäjän voisi uudelleenohjata takaisin lomakkeeseen tietyn viiveen jälkeen. Tämä voisi onnistua esimerkiksi JavaScriptiä käyttämällä asettamalla tämän [virheen osoittavan templaten](https://github.com/sapetus/Arvostelusovellus/blob/0de9b60c494cfdb7dad28121cecb3b5f5facdf6b/app/templates/error.html) loppuun:
    ```html
    <script>
        setTimeout(function(){
            window.location.href = '{{ redir_url }}';
        }, 2000);
    </script>
    ```
    Missä redir_url on lomakkeen sisältävä osoite ja aika on ilmoitettu millisekunteina (tässä tapauksessa uudelleenohjaus tapahtuu 2 sekunnin kuluttua). Jos käyttäjällä on JavaScript pois päältä tai et halua käyttää JavaScriptiä, niin tuon redir_url:n voi myös laittaa manuaalisesti klikattavaksi paluulinkiksi virhesivulle.

2. Lisättyä nimikettä ei voi enää muokata saati poistaa. Olisi mukavaa, jos käyttäjä, joka lisäsi nimikkeen, tai edes admin, voisi muokata tietoja lähettämisen jälkeen. Myöskin nimikkeiden poisto olisi hyvä lisä.

3. Olisi kiva, jos profiilissa olevien arvosteluiden yhteydessä olisi linkki, joka johtaisi kyseessä olevaan nimikkeeseen.

4. Profiilin asetussivulla olisi kiva, jos suosikkikategorian viimeisin valinta muistettaisiin, jotta suosikkikategoriaa ei tarvitsisi joka kerta erikseen asettaa, kun haluaa vaikka muuttaa profiilikuvaa. Lomakkeiden kentissä on erillinen attribuutti "value", jolla oletusarvoisen arvon pystyy asettamaan.

5. Käyttäjää ei tällä hetkellä pysty poistamaan, mutta oletan, että tämä on jo suunnitelmissa.

## Loppusanat
Alku on hyvin sujuva pienillä helposti korjattavilla ongelmilla. Sekä koodi että sovelluksen käyttö ovat helposti ymmärrettäviä. Jatka samaan malliin!

**Comment by sapetus** [comment]
Ongelmat korjattu ja QoL-ehdotukset toteutettu.
